[package]
name = "client-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
borsh = "0.9.1"
solana-sdk = "1.7.9"
solana-client = "1.7.9"
solana-cli-config = "1.7.9"